-- ==================================================================
-- SECTION 1 : GESTION DES ACCÈS (CREDENTIALS & PROFILS)
-- ==================================================================

DROP TABLE IF EXISTS auth_profiles CASCADE;
DROP TABLE IF EXISTS auth_cli CASCADE;
DROP TABLE IF EXISTS auth_snmp CASCADE;

CREATE TABLE auth_snmp (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    version         VARCHAR(10)  NOT NULL DEFAULT 'v2c',
    port            INTEGER      NOT NULL DEFAULT 161,
    community       VARCHAR(255),
    v3_user         VARCHAR(100),
    v3_level        VARCHAR(20),
    v3_auth_proto   VARCHAR(20),
    v3_auth_pass    VARCHAR(255),
    v3_priv_proto   VARCHAR(20),
    v3_priv_pass    VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_snmp_version    CHECK (version IN ('v1', 'v2c', 'v3')),
    CONSTRAINT chk_snmp_port       CHECK (port BETWEEN 1 AND 65535),
    CONSTRAINT chk_snmp_level      CHECK (v3_level IN ('noAuthNoPriv', 'authNoPriv', 'authPriv')),
    CONSTRAINT chk_snmp_auth_proto CHECK (v3_auth_proto IN ('MD5', 'SHA', 'SHA224', 'SHA256', 'SHA384', 'SHA512')),
    CONSTRAINT chk_snmp_priv_proto CHECK (v3_priv_proto IN ('DES', '3DES', 'AES', 'AES128', 'AES192', 'AES256'))
);

CREATE TABLE auth_cli (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    username        VARCHAR(100) NOT NULL,
    password        VARCHAR(255),
    enable_password VARCHAR(255),
    ssh_key_path    VARCHAR(255),
    protocol_pref   VARCHAR(10)  NOT NULL DEFAULT 'SSH',
    port            INTEGER      NOT NULL DEFAULT 22,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_cli_protocol CHECK (protocol_pref IN ('SSH', 'Telnet')),
    CONSTRAINT chk_cli_port     CHECK (port BETWEEN 1 AND 65535)
);

CREATE TABLE auth_profiles (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    snmp_id         INT,
    cli_id          INT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_profile_snmp FOREIGN KEY (snmp_id) REFERENCES auth_snmp(id) ON DELETE SET NULL,
    CONSTRAINT fk_profile_cli  FOREIGN KEY (cli_id)  REFERENCES auth_cli(id)  ON DELETE SET NULL
);

CREATE INDEX idx_auth_profiles_snmp ON auth_profiles(snmp_id);
CREATE INDEX idx_auth_profiles_cli  ON auth_profiles(cli_id);


-- ==================================================================
-- SECTION 2 : ORGANISATION & GROUPES
-- ==================================================================

DROP TABLE IF EXISTS device_groups_map CASCADE;
DROP TABLE IF EXISTS device_groups CASCADE;

CREATE TABLE device_groups (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    parent_id       INT,
    description     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_groups_parent FOREIGN KEY (parent_id) REFERENCES device_groups(id) ON DELETE SET NULL
);

CREATE TABLE device_groups_map (
    device_id       UUID NOT NULL,
    group_id        INT  NOT NULL,

    PRIMARY KEY (device_id, group_id),

    CONSTRAINT fk_map_group FOREIGN KEY (group_id) REFERENCES device_groups(id) ON DELETE CASCADE
    -- fk_map_device activée après Section 4
);

CREATE INDEX idx_device_groups_parent    ON device_groups(parent_id);
CREATE INDEX idx_device_groups_map_group ON device_groups_map(group_id);


-- ==================================================================
-- SECTION 3 : DICTIONNAIRE & NORMALISATION
-- ==================================================================

DROP TABLE IF EXISTS racks CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS device_models CASCADE;
DROP TABLE IF EXISTS device_families CASCADE;
DROP TABLE IF EXISTS device_categories CASCADE;
DROP TABLE IF EXISTS vendor_oui CASCADE;
DROP TABLE IF EXISTS vendor_iana_pen CASCADE;
DROP TABLE IF EXISTS vendors CASCADE;

CREATE TABLE vendors (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    slug            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_vendors_slug UNIQUE (slug)
);

CREATE TABLE vendor_iana_pen (
    pen             INT PRIMARY KEY,
    vendor_id       INT NOT NULL,

    CONSTRAINT fk_iana_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE
);

CREATE TABLE vendor_oui (
    mac_prefix      VARCHAR(6) PRIMARY KEY,
    vendor_id       INT NOT NULL,

    CONSTRAINT fk_oui_vendor   FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE CASCADE,
    CONSTRAINT chk_oui_length  CHECK (LENGTH(mac_prefix) = 6)
);

CREATE TABLE device_categories (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(50)  NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    icon_class      VARCHAR(100),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

CREATE TABLE device_families (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id       INT NOT NULL,
    category_id     INT NOT NULL,
    sysobject_oid   VARCHAR(100),
    name            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_family_vendor   FOREIGN KEY (vendor_id)   REFERENCES vendors(id)           ON DELETE CASCADE,
    CONSTRAINT fk_family_category FOREIGN KEY (category_id) REFERENCES device_categories(id) ON DELETE SET NULL
);

CREATE TABLE device_models (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id       INT NOT NULL,
    part_number     VARCHAR(100) NOT NULL,
    is_rackable     BOOLEAN DEFAULT TRUE,
    u_height        INT DEFAULT 1,
    is_eol          BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_model_family  FOREIGN KEY (family_id) REFERENCES device_families(id) ON DELETE CASCADE,
    CONSTRAINT chk_model_height CHECK (u_height > 0)
);

CREATE TABLE locations (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    parent_id       INT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_location_parent FOREIGN KEY (parent_id) REFERENCES locations(id) ON DELETE SET NULL
);

CREATE TABLE racks (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    height_u        INT NOT NULL DEFAULT 42,
    location_id     INT NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_rack_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE,
    CONSTRAINT chk_rack_height  CHECK (height_u > 0)
);

CREATE INDEX idx_vendor_iana_vendor ON vendor_iana_pen(vendor_id);
CREATE INDEX idx_vendor_oui_vendor ON vendor_oui(vendor_id);
CREATE INDEX idx_device_families_vendor ON device_families(vendor_id);
CREATE INDEX idx_device_families_category ON device_families(category_id);
CREATE INDEX idx_device_models_family ON device_models(family_id);
CREATE INDEX idx_locations_parent ON locations(parent_id);
CREATE INDEX idx_racks_location ON racks(location_id);


-- ==================================================================
-- SECTION 4 : INVENTAIRE PHYSIQUE
-- ==================================================================

DROP TABLE IF EXISTS device_services CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS device_modules CASCADE;
DROP TABLE IF EXISTS device_status CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS firmwares CASCADE;
DROP TABLE IF EXISTS ref_device_status CASCADE;

CREATE TABLE ref_device_status (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    color           VARCHAR(7)   DEFAULT '#6c757d',
    is_monitored    BOOLEAN DEFAULT TRUE,
    description     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_device_status_code UNIQUE (code)
);

CREATE TABLE firmwares (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         VARCHAR(100) NOT NULL,
    release_date    DATE,
    is_reference    BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE devices (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hostname         VARCHAR(255) NOT NULL,
    serial_number    VARCHAR(100),
    snmp_contact     VARCHAR(255),   -- sysContact SNMP
    snmp_description TEXT,           -- sysDescr SNMP complet

    model_id         INT  NOT NULL,
    firmware_id      INT,
    auth_profile_id  INT,
    status_id        INT  NOT NULL,

    location_id      INT,
    racks_id         INT,
    rack_position    INT,

    int_mgmt         BIGINT,         -- FK vers interfaces activée après Section 5

    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_device_model        FOREIGN KEY (model_id)        REFERENCES device_models(id)    ON DELETE RESTRICT,
    CONSTRAINT fk_device_firmware     FOREIGN KEY (firmware_id)     REFERENCES firmwares(id)        ON DELETE SET NULL,
    CONSTRAINT fk_device_auth_profile FOREIGN KEY (auth_profile_id) REFERENCES auth_profiles(id)   ON DELETE SET NULL,
    CONSTRAINT fk_device_status       FOREIGN KEY (status_id)       REFERENCES ref_device_status(id) ON DELETE RESTRICT,
    CONSTRAINT fk_device_location     FOREIGN KEY (location_id)     REFERENCES locations(id)       ON DELETE SET NULL,
    CONSTRAINT fk_device_rack         FOREIGN KEY (racks_id)        REFERENCES racks(id)           ON DELETE SET NULL,

    CONSTRAINT chk_device_location_exclusive
        CHECK (NOT (location_id IS NOT NULL AND racks_id IS NOT NULL))
);

CREATE TABLE device_status (
    device_id       UUID PRIMARY KEY,
    last_poll       TIMESTAMP WITH TIME ZONE,
    icmp_status     VARCHAR(20),
    snmp_status     VARCHAR(20),
    uptime_seconds  BIGINT,

    CONSTRAINT fk_status_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_status_icmp  CHECK (icmp_status IN ('Reachable', 'Unreachable')),
    CONSTRAINT chk_status_snmp  CHECK (snmp_status IN ('Reachable', 'Unreachable'))
);

CREATE TABLE device_modules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL,
    ent_index       INT,
    parent_index    BIGINT,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    class           VARCHAR(50),
    serial_number   VARCHAR(100),
    part_number     VARCHAR(100),
    is_fru          BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_module_device  FOREIGN KEY (device_id)    REFERENCES devices(id)        ON DELETE CASCADE,
    CONSTRAINT fk_module_parent  FOREIGN KEY (parent_index) REFERENCES device_modules(id) ON DELETE SET NULL,
    CONSTRAINT uq_device_module_ent_index UNIQUE (device_id, ent_index)
);

CREATE TABLE services (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    port            INT NOT NULL,
    protocol        VARCHAR(10) NOT NULL DEFAULT 'TCP',

    CONSTRAINT chk_service_port CHECK (port BETWEEN 1 AND 65535)
);

CREATE TABLE device_services (
    device_id       UUID   NOT NULL,
    service_id      INT    NOT NULL,
    ip_address_id   BIGINT,

    PRIMARY KEY (device_id, service_id),

    CONSTRAINT fk_devsvc_device  FOREIGN KEY (device_id)  REFERENCES devices(id)  ON DELETE CASCADE,
    CONSTRAINT fk_devsvc_service FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE
    -- fk_devsvc_ip activée après Section 6
);

CREATE INDEX idx_devices_model    ON devices(model_id);
CREATE INDEX idx_devices_status   ON devices(status_id);
CREATE INDEX idx_devices_location ON devices(location_id);
CREATE INDEX idx_devices_racks    ON devices(racks_id);
CREATE INDEX idx_devices_auth     ON devices(auth_profile_id);
CREATE INDEX idx_device_modules_device   ON device_modules(device_id);
CREATE INDEX idx_device_services_service ON device_services(service_id);

ALTER TABLE device_groups_map
    ADD CONSTRAINT fk_map_device
    FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE;


-- ==================================================================
-- SECTION 5 : INTERFACES & CONNECTIVITÉ L2
-- ==================================================================

DROP TABLE IF EXISTS stp_interface_state CASCADE;
DROP TABLE IF EXISTS stp_instances CASCADE;
DROP TABLE IF EXISTS lldp_neighbors CASCADE;
DROP TABLE IF EXISTS mac_address_table CASCADE;
DROP TABLE IF EXISTS interface_trunks CASCADE;
DROP TABLE IF EXISTS interface_vlans CASCADE;
DROP TABLE IF EXISTS vlans CASCADE;
DROP TABLE IF EXISTS lag_members CASCADE;
DROP TABLE IF EXISTS interfaces_poe CASCADE;
DROP TABLE IF EXISTS interface_port_security CASCADE;
DROP TABLE IF EXISTS interfaces_status CASCADE;
DROP TABLE IF EXISTS ip_interface_map CASCADE;
DROP TABLE IF EXISTS interfaces CASCADE;

CREATE TABLE interfaces (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID         NOT NULL,
    if_index        INT          NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    alias           VARCHAR(255),
    mac_address     MACADDR,
    type            VARCHAR(50),
    mtu             INT,
    speed           BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_interface_device       FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT uq_interface_device_ifindex UNIQUE (device_id, if_index)
);

CREATE TABLE ip_interface_map (
    interface_id    BIGINT  NOT NULL,
    ip_address_id   BIGINT  NOT NULL,
    is_primary      BOOLEAN DEFAULT FALSE,
    is_virtual      BOOLEAN DEFAULT FALSE,
    label           VARCHAR(100),

    PRIMARY KEY (interface_id, ip_address_id),

    CONSTRAINT fk_ipmap_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE
    -- fk_ipmap_ip activée après Section 6
);

CREATE TABLE interfaces_status (
    interface_id    BIGINT                   NOT NULL,
    last_change     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    admin_status    VARCHAR(10)              NOT NULL,
    oper_status     VARCHAR(10)              NOT NULL,

    PRIMARY KEY (interface_id, last_change),

    CONSTRAINT fk_status_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT chk_if_admin_status CHECK (admin_status IN ('Up', 'Down', 'Testing')),
    CONSTRAINT chk_if_oper_status  CHECK (oper_status  IN ('Up', 'Down', 'Testing', 'Unknown'))
);

CREATE TABLE interface_port_security (
    interface_id    BIGINT PRIMARY KEY,
    is_enabled      BOOLEAN DEFAULT FALSE,
    violation_mode  VARCHAR(20),
    max_macs        INT DEFAULT 1,
    current_macs    INT DEFAULT 0,
    violation_count INT DEFAULT 0,

    CONSTRAINT fk_psec_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT chk_psec_mode     CHECK (violation_mode IN ('Shutdown', 'Restrict', 'Protect'))
);

CREATE TABLE interfaces_poe (
    interface_id     BIGINT PRIMARY KEY,
    admin_status     BOOLEAN DEFAULT FALSE,
    detection_status VARCHAR(50),
    power_class      INT,

    CONSTRAINT fk_poe_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT chk_poe_class    CHECK (power_class BETWEEN 0 AND 4)
);

CREATE TABLE lag_members (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agg_interface_id      BIGINT NOT NULL,
    member_interface_id   BIGINT NOT NULL,
    protocol              VARCHAR(20) DEFAULT 'LACP',
    actor_oper_key        INT,
    partner_oper_system   VARCHAR(100),
    state_flags           VARCHAR(20),
    is_synced             BOOLEAN DEFAULT FALSE,
    is_standby            BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_lag_agg    FOREIGN KEY (agg_interface_id)    REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_lag_member FOREIGN KEY (member_interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT chk_lag_proto CHECK (protocol IN ('LACP', 'PAgP', 'Static')),

    -- Évite les doublons membre↔agrégat
    CONSTRAINT uq_lag_member UNIQUE (agg_interface_id, member_interface_id)
);

CREATE TABLE vlans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID        NOT NULL,
    vlan_tag        INT         NOT NULL,
    name            VARCHAR(100),
    status          VARCHAR(20) DEFAULT 'Active',
    type            VARCHAR(20) DEFAULT 'Ethernet',
    role            VARCHAR(20) DEFAULT 'Data',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_vlan_device   FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_vlan_tag     CHECK (vlan_tag BETWEEN 1 AND 4096),
    CONSTRAINT chk_vlan_status  CHECK (status IN ('Active', 'Suspended')),
    CONSTRAINT chk_vlan_type    CHECK (type IN ('Ethernet', 'FDDI', 'TokenRing', 'FDDI-Net', 'TrBRF', 'TrCRF')),
    CONSTRAINT chk_vlan_role    CHECK (role IN ('Data', 'Voice', 'Management', 'Guest', 'Blackhole')),
    CONSTRAINT uq_vlan_device_tag UNIQUE (device_id, vlan_tag)
);

CREATE TABLE interface_vlans (
    interface_id    BIGINT NOT NULL,
    vlan_id         BIGINT NOT NULL,
    mode            VARCHAR(20) DEFAULT 'Untagged',
    is_native       BOOLEAN DEFAULT FALSE,

    PRIMARY KEY (interface_id, vlan_id),

    CONSTRAINT fk_iv_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_iv_vlan      FOREIGN KEY (vlan_id)      REFERENCES vlans(id)      ON DELETE CASCADE,
    CONSTRAINT chk_iv_mode     CHECK (mode IN ('Untagged', 'Tagged', 'Native'))
);

CREATE TABLE interface_trunks (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_id    BIGINT NOT NULL,
    encapsulation   VARCHAR(20) DEFAULT 'dot1q',
    admin_status    VARCHAR(20),
    oper_status     VARCHAR(20),
    allowed_vlans   TEXT,
    pruning_enabled BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_trunk_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT uq_trunk_interface UNIQUE (interface_id)
);

CREATE TABLE mac_address_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_id    BIGINT  NOT NULL,
    mac_address     MACADDR NOT NULL,
    type            VARCHAR(20) DEFAULT 'Dynamic',
    last_seen       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_mac_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT chk_mac_type     CHECK (type IN ('Dynamic', 'Static', 'Self')),
    CONSTRAINT uq_mac_fdb_entry UNIQUE (interface_id, mac_address)
);

CREATE TABLE lldp_neighbors (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_interface_id  BIGINT       NOT NULL,
    remote_chassis_id   VARCHAR(255),
    remote_sysname      VARCHAR(255),
    remote_port_id      VARCHAR(255),
    remote_ip           VARCHAR(50),
    protocol            VARCHAR(10)  DEFAULT 'LLDP',
    last_seen           TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_lldp_interface FOREIGN KEY (local_interface_id) REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT chk_lldp_proto    CHECK (protocol IN ('LLDP', 'CDP')),

    -- Unicité sur (interface locale, sysname voisin, port voisin, protocole)
    -- remote_sysname est plus stable que remote_chassis_id (qui peut être NULL en CDP)
    CONSTRAINT uq_lldp_neighbor UNIQUE (local_interface_id, remote_sysname, remote_port_id, protocol)
);

CREATE TABLE stp_instances (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID   NOT NULL,
    vlan_id         BIGINT,
    root_bridge_id  VARCHAR(50),
    root_cost       INT,
    bridge_priority INT,

    CONSTRAINT fk_stp_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_stp_vlan   FOREIGN KEY (vlan_id)   REFERENCES vlans(id)   ON DELETE CASCADE
);

CREATE TABLE stp_interface_state (
    interface_id    BIGINT NOT NULL,
    stp_instance_id INT    NOT NULL,
    timestamp       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    state           VARCHAR(20),
    role            VARCHAR(20),

    PRIMARY KEY (interface_id, stp_instance_id),

    CONSTRAINT fk_stpis_interface FOREIGN KEY (interface_id)    REFERENCES interfaces(id)    ON DELETE CASCADE,
    CONSTRAINT fk_stpis_instance  FOREIGN KEY (stp_instance_id) REFERENCES stp_instances(id) ON DELETE CASCADE,
    CONSTRAINT chk_stp_state CHECK (state IN ('Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled')),
    CONSTRAINT chk_stp_role  CHECK (role  IN ('Root', 'Designated', 'Alternate', 'Backup', 'Master'))
);

CREATE INDEX idx_interfaces_device   ON interfaces(device_id);
CREATE INDEX idx_ip_map_interface    ON ip_interface_map(interface_id);
CREATE INDEX idx_lag_members_agg     ON lag_members(agg_interface_id);
CREATE INDEX idx_lag_members_mem     ON lag_members(member_interface_id);
CREATE INDEX idx_vlans_device        ON vlans(device_id);
CREATE INDEX idx_iv_vlan             ON interface_vlans(vlan_id);
CREATE INDEX idx_mac_table_interface ON mac_address_table(interface_id);
CREATE INDEX idx_mac_table_address   ON mac_address_table(mac_address);
CREATE INDEX idx_lldp_interface      ON lldp_neighbors(local_interface_id);
CREATE INDEX idx_stp_instances_device ON stp_instances(device_id);

-- Activer FK devices → interfaces (port de management)
ALTER TABLE devices
    ADD CONSTRAINT fk_device_int_mgmt
    FOREIGN KEY (int_mgmt) REFERENCES interfaces(id) ON DELETE SET NULL;


-- ==================================================================
-- SECTION 6 : LAYER 3 & IPAM
-- ==================================================================

DROP TABLE IF EXISTS l3_neighbors CASCADE;
DROP TABLE IF EXISTS ref_routing_protocols CASCADE;
DROP TABLE IF EXISTS redundancy_states CASCADE;
DROP TABLE IF EXISTS routing_table CASCADE;
DROP TABLE IF EXISTS arp_table CASCADE;
DROP TABLE IF EXISTS ip_addresses CASCADE;
DROP TABLE IF EXISTS ip_subnets CASCADE;
DROP TABLE IF EXISTS vrfs CASCADE;

CREATE TABLE vrfs (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID         NOT NULL,
    name            VARCHAR(100) NOT NULL,
    rd              VARCHAR(100),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_vrf_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

CREATE TABLE ip_subnets (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prefix          CIDR        NOT NULL,
    name            VARCHAR(100),
    vrf_global_id   INT,
    vlan_id         BIGINT,
    usage_percent   INT DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_subnet_vrf  FOREIGN KEY (vrf_global_id) REFERENCES vrfs(id)  ON DELETE SET NULL,
    CONSTRAINT fk_subnet_vlan FOREIGN KEY (vlan_id)       REFERENCES vlans(id) ON DELETE SET NULL,
    CONSTRAINT chk_subnet_usage CHECK (usage_percent BETWEEN 0 AND 100)
);

CREATE TABLE ip_addresses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address         INET         NOT NULL,
    subnet_id       INT,
    dns_name        VARCHAR(255),
    type            VARCHAR(20)  DEFAULT 'Static',
    status          VARCHAR(20)  DEFAULT 'Active',
    last_seen       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_ip_subnet  FOREIGN KEY (subnet_id) REFERENCES ip_subnets(id) ON DELETE CASCADE,
    CONSTRAINT chk_ip_type   CHECK (type   IN ('Static', 'DHCP', 'SLAAC', 'Reserved')),
    CONSTRAINT chk_ip_status CHECK (status IN ('Active', 'Reserved', 'Deprecated', 'Free')),
    CONSTRAINT uq_ip_address UNIQUE (address)
);

CREATE TABLE arp_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_id    BIGINT  NOT NULL,
    ip_address_id   BIGINT  NOT NULL,
    mac_address     MACADDR NOT NULL,
    last_seen       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_arp_entry   UNIQUE (interface_id, ip_address_id),
    CONSTRAINT fk_arp_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id)  ON DELETE CASCADE,
    CONSTRAINT fk_arp_ip        FOREIGN KEY (ip_address_id) REFERENCES ip_addresses(id) ON DELETE CASCADE
);

CREATE TABLE routing_table (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vrf_id          INT    NOT NULL,
    interface_id    BIGINT,
    dest_net        CIDR   NOT NULL,
    next_hop        INET,
    protocol        VARCHAR(20) DEFAULT 'Static',
    metric          INT DEFAULT 1,

    CONSTRAINT fk_route_vrf       FOREIGN KEY (vrf_id)       REFERENCES vrfs(id)       ON DELETE CASCADE,
    CONSTRAINT fk_route_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE
);

CREATE TABLE redundancy_states (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interface_id    BIGINT      NOT NULL,
    group_id        INT         NOT NULL,
    virtual_ip      INET,
    state           VARCHAR(50),
    priority        INT,
    active_router   UUID,
    protocol        VARCHAR(10) DEFAULT 'HSRP',  -- HSRP | VRRP
    preempt         BOOLEAN     DEFAULT FALSE,
    hello_time      INT,                          -- secondes
    hold_time       INT,                          -- secondes
    last_change     TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_redundancy_interface FOREIGN KEY (interface_id)  REFERENCES interfaces(id) ON DELETE CASCADE,
    CONSTRAINT fk_redundancy_active    FOREIGN KEY (active_router) REFERENCES devices(id)    ON DELETE SET NULL,
    CONSTRAINT chk_redundancy_state    CHECK (state IN ('Active', 'Standby', 'Listen', 'Init', 'Master', 'Backup')),
    CONSTRAINT uq_redundancy_group     UNIQUE (interface_id, group_id)
);

CREATE TABLE ref_routing_protocols (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(20) NOT NULL,
    name            VARCHAR(50) NOT NULL,
    default_port    INT,
    color           VARCHAR(7),

    CONSTRAINT uq_proto_slug UNIQUE (slug)
);

CREATE TABLE l3_neighbors (
    id                  INT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_interface_id  BIGINT NOT NULL,
    protocol_id         INT    NOT NULL,
    neighbor_ip_id      BIGINT,
    remote_router_id    VARCHAR(50),
    remote_as           BIGINT,
    state               VARCHAR(20),
    uptime_seconds      BIGINT,

    CONSTRAINT fk_neighbor_interface FOREIGN KEY (local_interface_id) REFERENCES interfaces(id)         ON DELETE CASCADE,
    CONSTRAINT fk_neighbor_proto     FOREIGN KEY (protocol_id)        REFERENCES ref_routing_protocols(id) ON DELETE RESTRICT,
    CONSTRAINT fk_neighbor_ip        FOREIGN KEY (neighbor_ip_id)     REFERENCES ip_addresses(id)       ON DELETE SET NULL
);

CREATE INDEX idx_vrfs_device      ON vrfs(device_id);
CREATE INDEX idx_subnets_vrf      ON ip_subnets(vrf_global_id);
CREATE INDEX idx_ip_subnet        ON ip_addresses(subnet_id);
CREATE INDEX idx_ip_address_val   ON ip_addresses(address);
CREATE INDEX idx_arp_interface    ON arp_table(interface_id);
CREATE INDEX idx_arp_ip           ON arp_table(ip_address_id);
CREATE INDEX idx_arp_mac          ON arp_table(mac_address);
CREATE INDEX idx_routing_vrf      ON routing_table(vrf_id);
CREATE INDEX idx_routing_dest     ON routing_table(dest_net);
CREATE INDEX idx_l3_neighbors_local ON l3_neighbors(local_interface_id);

-- Activer FK ip_interface_map → ip_addresses
ALTER TABLE ip_interface_map
    ADD CONSTRAINT fk_ipmap_ip
    FOREIGN KEY (ip_address_id) REFERENCES ip_addresses(id) ON DELETE CASCADE;

-- Activer FK device_services → ip_addresses
ALTER TABLE device_services
    ADD CONSTRAINT fk_devsvc_ip
    FOREIGN KEY (ip_address_id) REFERENCES ip_addresses(id) ON DELETE SET NULL;


-- ==================================================================
-- SECTION 7 : SUPERVISION & LOGS (MONITORING)
-- ==================================================================

DROP TABLE IF EXISTS maintenance_windows CASCADE;
DROP TABLE IF EXISTS alerts_active CASCADE;
DROP TABLE IF EXISTS system_events CASCADE;
DROP TABLE IF EXISTS interface_metrics_history CASCADE;
DROP TABLE IF EXISTS device_metrics_history CASCADE;
DROP TABLE IF EXISTS map_status CASCADE;
DROP TABLE IF EXISTS map_style_media CASCADE;
DROP TABLE IF EXISTS map_style_thickness CASCADE;
DROP TABLE IF EXISTS network_links CASCADE;
DROP TABLE IF EXISTS ref_alert_severity CASCADE;

CREATE TABLE ref_alert_severity (
    level   INT PRIMARY KEY,
    name    VARCHAR(50) NOT NULL,
    slug    VARCHAR(50) NOT NULL,
    color   VARCHAR(7)  DEFAULT '#000000',
    notify  BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_severity_slug UNIQUE (slug)
);

CREATE TABLE map_style_thickness (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50) NOT NULL,
    min_bps         BIGINT NOT NULL,
    max_bps         BIGINT NOT NULL,
    thickness_px    INT NOT NULL DEFAULT 1,

    CONSTRAINT chk_thickness_range CHECK (max_bps > min_bps)
);

CREATE TABLE map_style_media (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_type       VARCHAR(50) NOT NULL,
    base_color      VARCHAR(7)  NOT NULL,
    dash_array      VARCHAR(20),

    CONSTRAINT uq_style_media_type UNIQUE (link_type),
    CONSTRAINT chk_style_link_type CHECK (link_type IN ('Copper', 'Fiber', 'Wireless', 'Aggregate', 'Virtual', 'Backplane'))
);

CREATE TABLE map_status (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_type     VARCHAR(20) NOT NULL,
    color           VARCHAR(7)  NOT NULL,

    CONSTRAINT chk_map_metric CHECK (metric_type IN ('Up', 'Down', 'Degraded', 'Maintenance'))
);

CREATE TABLE network_links (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    src_interface_id    BIGINT NOT NULL,
    dst_interface_id    BIGINT NOT NULL,
    discovery_proto     VARCHAR(20) DEFAULT 'Manual',
    link_type           VARCHAR(50) DEFAULT 'Copper',
    media_subtype       VARCHAR(50),
    ui_color_static_id  INT,
    ui_thickness_id     INT,
    status_id           INT,
    is_locked           BOOLEAN DEFAULT FALSE,
    last_seen           TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_link_src         FOREIGN KEY (src_interface_id)   REFERENCES interfaces(id)        ON DELETE CASCADE,
    CONSTRAINT fk_link_dst         FOREIGN KEY (dst_interface_id)   REFERENCES interfaces(id)        ON DELETE CASCADE,
    CONSTRAINT fk_link_style_color FOREIGN KEY (ui_color_static_id) REFERENCES map_style_media(id)  ON DELETE SET NULL,
    CONSTRAINT fk_link_style_thick FOREIGN KEY (ui_thickness_id)    REFERENCES map_style_thickness(id) ON DELETE SET NULL,
    CONSTRAINT fk_link_status      FOREIGN KEY (status_id)          REFERENCES map_status(id)        ON DELETE SET NULL,

    CONSTRAINT chk_link_proto CHECK (discovery_proto IN ('LLDP', 'CDP', 'Manual', 'OSPF', 'BGP', 'Overlay')),
    CONSTRAINT chk_link_loop  CHECK (src_interface_id != dst_interface_id),

    -- Normalisation : src < dst pour unicité quel que soit le sens de découverte
    CONSTRAINT uq_network_link UNIQUE (src_interface_id, dst_interface_id)
);

CREATE TABLE device_metrics_history (
    time            TIMESTAMP WITH TIME ZONE NOT NULL,
    device_id       UUID NOT NULL,
    cpu_load        INT,
    ram_usage       INT,
    ram_free        INT,
    temp_celsius    INT,
    icmp_rtt        FLOAT,
    icmp_loss       INT,

    PRIMARY KEY (device_id, time),

    CONSTRAINT fk_metric_device  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_cpu_percent   CHECK (cpu_load  BETWEEN 0 AND 100),
    CONSTRAINT chk_ram_percent   CHECK (ram_usage BETWEEN 0 AND 100),
    CONSTRAINT chk_loss_percent  CHECK (icmp_loss BETWEEN 0 AND 100)
);

CREATE TABLE interface_metrics_history (
    time              TIMESTAMP WITH TIME ZONE NOT NULL,
    interface_id      BIGINT NOT NULL,

    -- Compteurs bruts IF-MIB (64-bit HC en priorité, 32-bit sinon)
    in_octets         BIGINT,   -- ifHCInOctets / ifInOctets
    out_octets        BIGINT,   -- ifHCOutOctets / ifOutOctets
    in_ucast_pkts     BIGINT,   -- ifHCInUcastPkts / ifInUcastPkts
    out_ucast_pkts    BIGINT,   -- ifHCOutUcastPkts / ifOutUcastPkts
    in_nucast_pkts    BIGINT,   -- ifInNUcastPkts (multicast + broadcast)
    out_nucast_pkts   BIGINT,   -- ifOutNUcastPkts
    in_errors         INT,      -- ifInErrors
    out_errors        INT,      -- ifOutErrors
    in_discards       INT,      -- ifInDiscards
    out_discards      INT,      -- ifOutDiscards
    in_unknown_protos INT,      -- ifInUnknownProtos

    -- Débits calculés (optionnel — calculable depuis delta octets/temps)
    in_bps            BIGINT,
    out_bps           BIGINT,

    -- PoE
    consumption_w     FLOAT,

    PRIMARY KEY (interface_id, time),

    CONSTRAINT fk_metric_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE CASCADE
);

CREATE TABLE system_events (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time            TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    device_id       UUID NOT NULL,
    severity        INT  DEFAULT 6,
    facility        VARCHAR(20),
    source_type     VARCHAR(20) DEFAULT 'Syslog',
    message         TEXT,
    processed       BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_event_device  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_event_severity CHECK (severity BETWEEN 0 AND 7),
    CONSTRAINT chk_event_source   CHECK (source_type IN ('Syslog', 'SNMP_Trap', 'SNMP_Inform', 'Internal', 'API'))
);

CREATE TABLE alerts_active (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL,
    object_ref      VARCHAR(255),
    severity_level  INT  NOT NULL,
    message         TEXT,
    start_time      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    count           INT DEFAULT 1,
    ack_by_user_id  INT,
    ack_at          TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_alert_device   FOREIGN KEY (device_id)     REFERENCES devices(id)          ON DELETE CASCADE,
    CONSTRAINT fk_alert_severity FOREIGN KEY (severity_level) REFERENCES ref_alert_severity(level) ON DELETE RESTRICT
    -- fk_alert_user activée après Section 11
);

CREATE TABLE maintenance_windows (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL,
    description     TEXT,
    start_time      TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time        TIMESTAMP WITH TIME ZONE NOT NULL,
    suppress_alerts BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_maint_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_maint_dates CHECK (end_time > start_time)
);

CREATE INDEX idx_links_src           ON network_links(src_interface_id);
CREATE INDEX idx_links_dst           ON network_links(dst_interface_id);
CREATE INDEX idx_hist_device_time    ON device_metrics_history(device_id, time DESC);
CREATE INDEX idx_hist_int_time       ON interface_metrics_history(interface_id, time DESC);
CREATE INDEX idx_events_device_time  ON system_events(device_id, time DESC);
CREATE INDEX idx_alerts_device       ON alerts_active(device_id);
CREATE INDEX idx_maint_device        ON maintenance_windows(device_id);
CREATE INDEX idx_maint_dates         ON maintenance_windows(start_time, end_time);


-- ==================================================================
-- SECTION 8 : ADMINISTRATION À DISTANCE (AUTOMATION)
-- ==================================================================

DROP TABLE IF EXISTS device_tags_map CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS device_backups CASCADE;
DROP TABLE IF EXISTS job_results CASCADE;
DROP TABLE IF EXISTS devices_jobs CASCADE;
DROP TABLE IF EXISTS config_jobs CASCADE;

CREATE TABLE tags (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key     VARCHAR(50) NOT NULL,
    value   VARCHAR(50) NOT NULL,
    color   VARCHAR(7)  DEFAULT '#17a2b8',

    CONSTRAINT uq_tags_key_value UNIQUE (key, value)
);

CREATE TABLE device_tags_map (
    device_id   UUID NOT NULL,
    tag_id      INT  NOT NULL,

    PRIMARY KEY (device_id, tag_id),

    CONSTRAINT fk_tagmap_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_tagmap_tag    FOREIGN KEY (tag_id)    REFERENCES tags(id)    ON DELETE CASCADE
);

CREATE TABLE device_backups (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       UUID NOT NULL,
    collected_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    config_type     VARCHAR(20) DEFAULT 'Running',
    content         TEXT,
    hash            VARCHAR(64),
    diff_previous   TEXT,

    CONSTRAINT fk_backup_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT chk_backup_type  CHECK (config_type IN ('Running', 'Startup', 'Vlan.dat'))
);

CREATE TABLE config_jobs (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    created_by      INT,
    scheduled_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    commands        TEXT NOT NULL,
    global_status   VARCHAR(20) DEFAULT 'Scheduled',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_job_status CHECK (global_status IN ('Scheduled', 'Processing', 'Finished', 'Draft', 'Cancelled'))
    -- fk_job_creator activée après Section 11
);

CREATE TABLE devices_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      INT    NOT NULL,
    device_id   UUID   NOT NULL,
    status      VARCHAR(20) DEFAULT 'Pending',
    retry_count INT DEFAULT 0,

    CONSTRAINT fk_dj_job    FOREIGN KEY (job_id)    REFERENCES config_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_dj_device FOREIGN KEY (device_id) REFERENCES devices(id)    ON DELETE CASCADE,
    CONSTRAINT chk_dj_status CHECK (status IN ('Pending', 'Queued', 'Running', 'Completed', 'Failed', 'Unreachable'))
);

CREATE TABLE job_results (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_device_id   BIGINT  NOT NULL,
    output          TEXT,
    is_success      BOOLEAN DEFAULT FALSE,
    executed_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    finished_at     TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_result_jobdev FOREIGN KEY (job_device_id) REFERENCES devices_jobs(id) ON DELETE CASCADE
);

CREATE INDEX idx_tagmap_tag    ON device_tags_map(tag_id);
CREATE INDEX idx_backups_device ON device_backups(device_id);
CREATE INDEX idx_backups_hash   ON device_backups(hash);
CREATE INDEX idx_dj_job         ON devices_jobs(job_id);
CREATE INDEX idx_dj_device      ON devices_jobs(device_id);
CREATE INDEX idx_results_jobdev ON job_results(job_device_id);


-- ==================================================================
-- SECTION 9 : LIAISONS OPÉRATEURS (WAN)
-- ==================================================================

DROP TABLE IF EXISTS circuits CASCADE;
DROP TABLE IF EXISTS providers CASCADE;

CREATE TABLE providers (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    account_number  VARCHAR(100),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE circuits (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     INT    NOT NULL,
    reference       VARCHAR(100) NOT NULL,
    interface_id    BIGINT,
    type            VARCHAR(50) DEFAULT 'MPLS',
    bandwidth_mbps  INT,
    contract_end    DATE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_circuit_provider  FOREIGN KEY (provider_id)  REFERENCES providers(id)  ON DELETE RESTRICT,
    CONSTRAINT fk_circuit_interface FOREIGN KEY (interface_id) REFERENCES interfaces(id) ON DELETE SET NULL,
    CONSTRAINT chk_circuit_type     CHECK (type IN ('MPLS', 'Internet', 'DarkFiber', '4G', '5G', 'Satellite', 'Wave', 'SD-WAN'))
);

CREATE INDEX idx_circuits_provider ON circuits(provider_id);
CREATE INDEX idx_circuits_interface ON circuits(interface_id);
CREATE INDEX idx_circuits_end_date  ON circuits(contract_end);


-- ==================================================================
-- SECTION 10 : CYCLE DE VIE (LCM)
-- ==================================================================

DROP TABLE IF EXISTS device_contracts_map CASCADE;
DROP TABLE IF EXISTS contracts CASCADE;

CREATE TABLE contracts (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    provider_id     INT  NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    description     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_contract_provider FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE RESTRICT,
    CONSTRAINT chk_contract_dates   CHECK (end_date > start_date)
);

CREATE TABLE device_contracts_map (
    contract_id INT  NOT NULL,
    device_id   UUID NOT NULL,

    PRIMARY KEY (contract_id, device_id),

    CONSTRAINT fk_map_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_map_device   FOREIGN KEY (device_id)   REFERENCES devices(id)   ON DELETE CASCADE
);

CREATE INDEX idx_contracts_provider ON contracts(provider_id);
CREATE INDEX idx_contracts_end_date ON contracts(end_date);
CREATE INDEX idx_dcm_device         ON device_contracts_map(device_id);


-- ==================================================================
-- SECTION 11 : IDENTITÉ & GROUPES (IAM)
-- ==================================================================

DROP TABLE IF EXISTS user_group_members CASCADE;
DROP TABLE IF EXISTS user_groups CASCADE;
DROP TABLE IF EXISTS app_users_pwd CASCADE;
DROP TABLE IF EXISTS app_users CASCADE;

CREATE TABLE app_users (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    first_name      VARCHAR(100),
    last_name       VARCHAR(100),
    auth_source     VARCHAR(20)  DEFAULT 'Local',
    external_uid    VARCHAR(255),
    is_active       BOOLEAN DEFAULT TRUE,
    is_super_admin  BOOLEAN DEFAULT FALSE,
    last_login      TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_user_username     UNIQUE (username),
    CONSTRAINT uq_user_email        UNIQUE (email),
    CONSTRAINT uq_user_external_uid UNIQUE (external_uid),
    CONSTRAINT chk_user_auth_source CHECK (auth_source IN ('Local', 'LDAP', 'SAML', 'API_Token'))
);

CREATE TABLE app_users_pwd (
    user_id         INT PRIMARY KEY,
    password_hash   VARCHAR(255) NOT NULL,
    must_change_pwd BOOLEAN DEFAULT FALSE,
    last_change     TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_pwd_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
);

CREATE TABLE user_groups (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    description TEXT,
    is_builtin  BOOLEAN DEFAULT FALSE,
    priority    INT DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_group_slug UNIQUE (slug)
);

CREATE TABLE user_group_members (
    user_id     INT NOT NULL,
    group_id    INT NOT NULL,
    added_via   VARCHAR(20) DEFAULT 'Manual',
    added_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    PRIMARY KEY (user_id, group_id),

    CONSTRAINT fk_member_user  FOREIGN KEY (user_id)  REFERENCES app_users(id)   ON DELETE CASCADE,
    CONSTRAINT fk_member_group FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE CASCADE,
    CONSTRAINT chk_member_source CHECK (added_via IN ('Manual', 'LDAP_Sync', 'SAML_Attr'))
);

CREATE INDEX idx_users_auth_source    ON app_users(auth_source);
CREATE INDEX idx_group_members_group  ON user_group_members(group_id);

-- Activer FK alerts_active → app_users
ALTER TABLE alerts_active
    ADD CONSTRAINT fk_alert_user
    FOREIGN KEY (ack_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL;

-- Activer FK config_jobs → app_users
ALTER TABLE config_jobs
    ADD CONSTRAINT fk_job_creator
    FOREIGN KEY (created_by) REFERENCES app_users(id) ON DELETE SET NULL;


-- ==================================================================
-- SECTION 12 : INTÉGRATION LDAP / ACTIVE DIRECTORY
-- ==================================================================

DROP TABLE IF EXISTS ldap_group_mappings CASCADE;
DROP TABLE IF EXISTS auth_providers CASCADE;

CREATE TABLE auth_providers (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    type                VARCHAR(20)  NOT NULL,
    hostname            VARCHAR(255) NOT NULL,
    port                INT NOT NULL DEFAULT 389,
    encryption          VARCHAR(20) DEFAULT 'None',
    bind_dn             VARCHAR(255),
    bind_password       VARCHAR(255),
    base_dn             VARCHAR(255) NOT NULL,
    user_search_filter  TEXT,
    attributes_map      JSONB DEFAULT '{}'::jsonb,
    sync_enabled        BOOLEAN DEFAULT FALSE,
    sync_interval       INT DEFAULT 60,
    last_sync_status    VARCHAR(20),
    last_sync_log       TEXT,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_auth_type       CHECK (type       IN ('ActiveDirectory', 'OpenLDAP')),
    CONSTRAINT chk_auth_enc        CHECK (encryption IN ('None', 'StartTLS', 'SSL')),
    CONSTRAINT chk_auth_sync_status CHECK (last_sync_status IN ('Success', 'Failed', 'Running'))
);

CREATE TABLE ldap_group_mappings (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     INT NOT NULL,
    ldap_group_dn   VARCHAR(255) NOT NULL,
    local_group_id  INT NOT NULL,

    CONSTRAINT fk_mapping_provider FOREIGN KEY (provider_id)    REFERENCES auth_providers(id) ON DELETE CASCADE,
    CONSTRAINT fk_mapping_group    FOREIGN KEY (local_group_id) REFERENCES user_groups(id)    ON DELETE CASCADE,
    CONSTRAINT uq_ldap_mapping     UNIQUE (provider_id, ldap_group_dn, local_group_id)
);

CREATE INDEX idx_ldap_mapping_provider ON ldap_group_mappings(provider_id);
CREATE INDEX idx_ldap_mapping_local    ON ldap_group_mappings(local_group_id);


-- ==================================================================
-- SECTION 13 : ACL & PERMISSIONS (RBAC)
-- ==================================================================

DROP TABLE IF EXISTS access_policies CASCADE;
DROP TABLE IF EXISTS role_permissions CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE roles (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    is_system   BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE permissions (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL,
    module      VARCHAR(50)  NOT NULL,
    description VARCHAR(255),

    CONSTRAINT uq_perm_code UNIQUE (code)
);

CREATE TABLE role_permissions (
    role_id       INT NOT NULL,
    permission_id INT NOT NULL,

    PRIMARY KEY (role_id, permission_id),

    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles(id)       ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE access_policies (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name         VARCHAR(100),
    subject_id          INT NOT NULL,
    role_id             INT NOT NULL,
    is_denied           BOOLEAN DEFAULT FALSE,
    scope_type          VARCHAR(20) NOT NULL DEFAULT 'Global',
    ref_device_id       UUID,
    ref_device_group_id INT,
    ref_location_id     INT,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_policy_subject  FOREIGN KEY (subject_id)          REFERENCES user_groups(id)   ON DELETE CASCADE,
    CONSTRAINT fk_policy_role     FOREIGN KEY (role_id)             REFERENCES roles(id)          ON DELETE CASCADE,
    CONSTRAINT fk_policy_device   FOREIGN KEY (ref_device_id)       REFERENCES devices(id)        ON DELETE CASCADE,
    CONSTRAINT fk_policy_group    FOREIGN KEY (ref_device_group_id) REFERENCES device_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_policy_location FOREIGN KEY (ref_location_id)     REFERENCES locations(id)     ON DELETE CASCADE,

    CONSTRAINT chk_policy_scope_type CHECK (scope_type IN ('Global', 'Device', 'DeviceGroup', 'Location')),
    CONSTRAINT chk_policy_global     CHECK (
        scope_type != 'Global' OR
        (ref_device_id IS NULL AND ref_device_group_id IS NULL AND ref_location_id IS NULL)
    )
);

CREATE INDEX idx_policy_subject  ON access_policies(subject_id);
CREATE INDEX idx_policy_device   ON access_policies(ref_device_id);
CREATE INDEX idx_policy_group    ON access_policies(ref_device_group_id);
CREATE INDEX idx_policy_location ON access_policies(ref_location_id);


-- ==================================================================
-- SECTION 14 : LOGS DE SÉCURITÉ & ACCÈS
-- ==================================================================

DROP TABLE IF EXISTS logs_security_alerts CASCADE;
DROP TABLE IF EXISTS logs_auth_sessions CASCADE;
DROP TABLE IF EXISTS ref_security_events CASCADE;

CREATE TABLE ref_security_events (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(100) NOT NULL,
    name         VARCHAR(100) NOT NULL,
    category     VARCHAR(50)  NOT NULL,
    risk_level   VARCHAR(20)  DEFAULT 'Low',
    is_alertable BOOLEAN DEFAULT FALSE,

    CONSTRAINT uq_secevent_slug  UNIQUE (slug),
    CONSTRAINT chk_secevent_risk CHECK (risk_level IN ('High', 'Medium', 'Low', 'Critical'))
);

CREATE TABLE logs_auth_sessions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INT,
    attempted_username  VARCHAR(100),
    source_ip           INET,
    user_agent          TEXT,
    status              VARCHAR(50) NOT NULL,
    auth_method         VARCHAR(20) DEFAULT 'Local',
    session_id          VARCHAR(255),
    login_at            TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    logout_at           TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_log_session_user    FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE SET NULL,
    CONSTRAINT chk_log_session_status CHECK (status IN ('Success', 'Failed_BadPwd', 'Failed_Locked', 'Failed_MFA', 'Failed_Unknown', 'Expired')),
    CONSTRAINT chk_log_session_method CHECK (auth_method IN ('Local', 'LDAP', 'SAML', 'API_Token', 'SSO'))
);

CREATE TABLE logs_security_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id         INT,
    event_id        INT NOT NULL,
    target_user_id  INT,
    description     TEXT,
    ip_address      INET,
    user_agent      TEXT,

    CONSTRAINT fk_sec_log_user   FOREIGN KEY (user_id)        REFERENCES app_users(id)        ON DELETE SET NULL,
    CONSTRAINT fk_sec_log_target FOREIGN KEY (target_user_id) REFERENCES app_users(id)        ON DELETE SET NULL,
    CONSTRAINT fk_sec_log_event  FOREIGN KEY (event_id)       REFERENCES ref_security_events(id) ON DELETE RESTRICT
);

CREATE INDEX idx_logs_auth_time  ON logs_auth_sessions(login_at DESC);
CREATE INDEX idx_logs_auth_user  ON logs_auth_sessions(user_id);
CREATE INDEX idx_logs_auth_ip    ON logs_auth_sessions(source_ip);
CREATE INDEX idx_logs_sec_time   ON logs_security_alerts(timestamp DESC);
CREATE INDEX idx_logs_sec_user   ON logs_security_alerts(user_id);
CREATE INDEX idx_logs_sec_event  ON logs_security_alerts(event_id);


-- ==================================================================
-- SECTION 15 : AUDIT DES DONNÉES (AUDIT TRAIL)
-- ==================================================================

DROP TABLE IF EXISTS logs_audit_trail CASCADE;

CREATE TABLE logs_audit_trail (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id   UUID,
    actor_user_id    INT,
    client_ip        INET,
    action_type      VARCHAR(10) NOT NULL,
    table_name       VARCHAR(50) NOT NULL,
    record_id_text   VARCHAR(100) NOT NULL,
    changes          JSONB,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ref_device_id    UUID,
    ref_interface_id BIGINT,
    ref_subnet_id    INT,
    ref_location_id  INT,
    ref_user_id      INT,
    ref_group_id     INT,
    ref_auth_snmp_id INT,
    ref_auth_cli_id  INT,
    ref_vlan_id      BIGINT,
    ref_circuit_id   INT,

    CONSTRAINT fk_audit_actor     FOREIGN KEY (actor_user_id)    REFERENCES app_users(id)   ON DELETE SET NULL,
    CONSTRAINT fk_audit_device    FOREIGN KEY (ref_device_id)    REFERENCES devices(id)     ON DELETE SET NULL,
    CONSTRAINT fk_audit_interface FOREIGN KEY (ref_interface_id) REFERENCES interfaces(id)  ON DELETE SET NULL,
    CONSTRAINT fk_audit_subnet    FOREIGN KEY (ref_subnet_id)    REFERENCES ip_subnets(id)  ON DELETE SET NULL,
    CONSTRAINT fk_audit_location  FOREIGN KEY (ref_location_id)  REFERENCES locations(id)   ON DELETE SET NULL,
    CONSTRAINT fk_audit_ref_user  FOREIGN KEY (ref_user_id)      REFERENCES app_users(id)   ON DELETE SET NULL,
    CONSTRAINT fk_audit_group     FOREIGN KEY (ref_group_id)     REFERENCES device_groups(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_snmp      FOREIGN KEY (ref_auth_snmp_id) REFERENCES auth_snmp(id)   ON DELETE SET NULL,
    CONSTRAINT fk_audit_cli       FOREIGN KEY (ref_auth_cli_id)  REFERENCES auth_cli(id)    ON DELETE SET NULL,
    CONSTRAINT fk_audit_vlan      FOREIGN KEY (ref_vlan_id)      REFERENCES vlans(id)       ON DELETE SET NULL,
    CONSTRAINT fk_audit_circuit   FOREIGN KEY (ref_circuit_id)   REFERENCES circuits(id)    ON DELETE SET NULL,
    CONSTRAINT chk_audit_action   CHECK (action_type IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE INDEX idx_audit_time         ON logs_audit_trail(created_at DESC);
CREATE INDEX idx_audit_actor        ON logs_audit_trail(actor_user_id);
CREATE INDEX idx_audit_table_record ON logs_audit_trail(table_name, record_id_text);
CREATE INDEX idx_audit_ref_device    ON logs_audit_trail(ref_device_id)    WHERE ref_device_id    IS NOT NULL;
CREATE INDEX idx_audit_ref_interface ON logs_audit_trail(ref_interface_id) WHERE ref_interface_id IS NOT NULL;
CREATE INDEX idx_audit_ref_subnet    ON logs_audit_trail(ref_subnet_id)    WHERE ref_subnet_id    IS NOT NULL;
CREATE INDEX idx_audit_ref_user      ON logs_audit_trail(ref_user_id)      WHERE ref_user_id      IS NOT NULL;


-- ==================================================================
-- SECTION 16 : ARCHIVAGE & RÉTENTION DES LOGS
-- ==================================================================

DROP TABLE IF EXISTS logs_retention_policy CASCADE;

CREATE TABLE logs_retention_policy (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_table       VARCHAR(100) NOT NULL,
    retention_days  INT NOT NULL DEFAULT 365,
    archive_status  BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_retention_table   UNIQUE (log_table),
    CONSTRAINT chk_retention_days   CHECK (retention_days >= 1)
);


-- ==================================================================
-- SECTION 17 : LOGS OPÉRATIONNELS
-- ==================================================================

DROP TABLE IF EXISTS logs_operations CASCADE;

CREATE TABLE logs_operations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performed_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id             INT,
    action_code         VARCHAR(100) NOT NULL,
    status              VARCHAR(20)  DEFAULT 'Pending',
    execution_time_ms   INT,
    message             TEXT,
    job_result_id       BIGINT,
    ref_device_id       UUID,
    ref_interface_id    BIGINT,
    ref_group_id        INT,

    CONSTRAINT fk_op_user       FOREIGN KEY (user_id)          REFERENCES app_users(id)   ON DELETE SET NULL,
    CONSTRAINT fk_op_job_result FOREIGN KEY (job_result_id)    REFERENCES job_results(id) ON DELETE SET NULL,
    CONSTRAINT fk_op_device     FOREIGN KEY (ref_device_id)    REFERENCES devices(id)     ON DELETE SET NULL,
    CONSTRAINT fk_op_interface  FOREIGN KEY (ref_interface_id) REFERENCES interfaces(id)  ON DELETE SET NULL,
    CONSTRAINT fk_op_group      FOREIGN KEY (ref_group_id)     REFERENCES device_groups(id) ON DELETE SET NULL,
    CONSTRAINT chk_op_status    CHECK (status IN ('Pending', 'Success', 'Failure', 'Timeout', 'Cancelled'))
);

CREATE INDEX idx_ops_time      ON logs_operations(performed_at DESC);
CREATE INDEX idx_ops_user      ON logs_operations(user_id);
CREATE INDEX idx_ops_device    ON logs_operations(ref_device_id) WHERE ref_device_id IS NOT NULL;


-- ==================================================================
-- SECTION 18 : LOGS DE CONSULTATION (ACCESS VIEW AUDIT)
-- ==================================================================

DROP TABLE IF EXISTS logs_access_views CASCADE;
DROP TABLE IF EXISTS ref_view_types CASCADE;

CREATE TABLE ref_view_types (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             VARCHAR(100) NOT NULL,
    name             VARCHAR(100) NOT NULL,
    data_sensitivity VARCHAR(20)  DEFAULT 'Internal',

    CONSTRAINT uq_view_slug         UNIQUE (slug),
    CONSTRAINT chk_view_sensitivity CHECK (data_sensitivity IN ('Public', 'Internal', 'Confidential', 'Secret'))
);

CREATE TABLE logs_access_views (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewed_at           TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_id             INT,
    ip_address          INET,
    type_id             INT NOT NULL,
    resource_name       VARCHAR(255),
    ref_device_id       UUID,
    ref_auth_snmp_id    INT,
    ref_auth_cli_id     INT,
    ref_auth_profile_id INT,

    CONSTRAINT fk_view_user    FOREIGN KEY (user_id)             REFERENCES app_users(id)    ON DELETE SET NULL,
    CONSTRAINT fk_view_type    FOREIGN KEY (type_id)             REFERENCES ref_view_types(id) ON DELETE RESTRICT,
    CONSTRAINT fk_view_device  FOREIGN KEY (ref_device_id)       REFERENCES devices(id)       ON DELETE SET NULL,
    CONSTRAINT fk_view_snmp    FOREIGN KEY (ref_auth_snmp_id)    REFERENCES auth_snmp(id)     ON DELETE SET NULL,
    CONSTRAINT fk_view_cli     FOREIGN KEY (ref_auth_cli_id)     REFERENCES auth_cli(id)      ON DELETE SET NULL,
    CONSTRAINT fk_view_profile FOREIGN KEY (ref_auth_profile_id) REFERENCES auth_profiles(id) ON DELETE SET NULL
);

CREATE INDEX idx_views_time ON logs_access_views(viewed_at DESC);
CREATE INDEX idx_views_user ON logs_access_views(user_id);
CREATE INDEX idx_views_type ON logs_access_views(type_id);


-- ==================================================================
-- SECTION 19 : MOTEUR DE SCAN (DISCOVERY)
-- ==================================================================

DROP TABLE IF EXISTS snmp_credentials_mapping CASCADE;
DROP TABLE IF EXISTS scan_networks CASCADE;
DROP TABLE IF EXISTS scan_profiles CASCADE;

CREATE TABLE scan_profiles (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(100) NOT NULL,
    type                VARCHAR(50)  NOT NULL,

    -- Fréquence (uniquement pour SNMP_Discovery sur scan_networks)
    -- Les autres types sont gérés via monitoring_profiles
    interval_seconds    INT NOT NULL DEFAULT 3600,

    timeout_ms          INT DEFAULT 2000,
    retry_count         INT DEFAULT 1,
    concurrency_threads INT DEFAULT 10,
    packet_delay_ms     INT DEFAULT 0,
    is_enabled          BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_scan_type CHECK (type IN (
        'SNMP_Discovery',   -- Découverte complète d'un subnet
        'ICMP_Ping',        -- Ping subnet (usage limité — préférer monitoring_profiles)
        'Port_Scan',        -- Scan de ports TCP
        'SNMP_Metrics',     -- Usage limité — préférer monitoring_profiles
        'SNMP_Full'         -- Usage limité — préférer monitoring_profiles
    )),
    CONSTRAINT chk_scan_params CHECK (timeout_ms > 0 AND retry_count >= 0 AND concurrency_threads > 0),
    CONSTRAINT chk_interval    CHECK (interval_seconds >= 0)
);

CREATE TABLE scan_networks (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subnet              CIDR    NOT NULL,
    exclude_ips         JSONB   DEFAULT '[]'::jsonb,
    description         VARCHAR(255),
    scan_profile_id     INT     NOT NULL,
    auth_profile_id     INT     NOT NULL,
    next_scan_at        TIMESTAMP WITH TIME ZONE,
    interval_seconds    INT     NOT NULL DEFAULT 86400,  -- 24h par défaut pour les découvertes
    last_scan_status    VARCHAR(20) DEFAULT 'idle',
    last_scan_at        TIMESTAMP WITH TIME ZONE,
    last_scan_duration  INT,
    last_hosts_found    INT DEFAULT 0,
    last_error          TEXT,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_scan_net_scan_profile FOREIGN KEY (scan_profile_id) REFERENCES scan_profiles(id)  ON DELETE RESTRICT,
    CONSTRAINT fk_scan_net_auth_profile FOREIGN KEY (auth_profile_id) REFERENCES auth_profiles(id) ON DELETE RESTRICT,
    CONSTRAINT chk_scan_net_status      CHECK (last_scan_status IN ('idle', 'running', 'completed', 'failed')),

    -- Unicité : même subnet peut être configuré avec des profils auth différents
    --          ou des profils de scan différents
    CONSTRAINT uq_scan_network_subnet_profile UNIQUE (subnet, auth_profile_id, scan_profile_id)
);

CREATE TABLE snmp_credentials_mapping (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subnet          CIDR NOT NULL,
    auth_profile_id INT  NOT NULL,
    priority        INT  DEFAULT 10,

    CONSTRAINT fk_map_auth_profile FOREIGN KEY (auth_profile_id) REFERENCES auth_profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_scan_networks_scan_profile ON scan_networks(scan_profile_id);
CREATE INDEX idx_scan_networks_auth_profile ON scan_networks(auth_profile_id);
CREATE INDEX idx_scan_networks_status       ON scan_networks(last_scan_status);
CREATE INDEX idx_scan_networks_next_scan    ON scan_networks(next_scan_at);
CREATE INDEX idx_snmp_map_subnet            ON snmp_credentials_mapping(subnet);
CREATE INDEX idx_snmp_map_profile           ON snmp_credentials_mapping(auth_profile_id);


-- ==================================================================
-- SECTION 20 : CONFIGURATION SYSTÈME & RÉTENTION
-- ==================================================================

DROP TABLE IF EXISTS data_retention_policies CASCADE;

CREATE TABLE data_retention_policies (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name      VARCHAR(100) NOT NULL,
    retention_days  INT NOT NULL DEFAULT 365,
    is_enabled      BOOLEAN DEFAULT TRUE,
    last_cleanup    TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uq_data_retention_table UNIQUE (table_name),
    CONSTRAINT chk_data_retention_days CHECK (retention_days >= 1)
);


-- ==================================================================
-- SECTION 20b : MONITORING RÉCURRENT (PROFILS & TÂCHES)
-- ==================================================================

DROP TABLE IF EXISTS device_monitoring_tasks CASCADE;
DROP TABLE IF EXISTS monitoring_profiles CASCADE;

CREATE TABLE monitoring_profiles (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100) NOT NULL,
    scan_type        VARCHAR(50)  NOT NULL,
    interval_seconds INT NOT NULL DEFAULT 300,
    timeout_ms       INT NOT NULL DEFAULT 2000,
    retry_count      INT NOT NULL DEFAULT 1,
    is_enabled       BOOLEAN DEFAULT TRUE,
    description      TEXT,
    created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_mp_type     CHECK (scan_type IN ('ICMP_Ping', 'SNMP_Metrics', 'LLDP_Topology', 'SNMP_Full')),
    CONSTRAINT chk_mp_interval CHECK (interval_seconds > 0),
    CONSTRAINT uq_monitoring_profile_name UNIQUE (name)
);

CREATE TABLE device_monitoring_tasks (
    device_id            UUID NOT NULL,
    profile_id           INT  NOT NULL,
    is_enabled           BOOLEAN DEFAULT TRUE,
    next_run_at          TIMESTAMP WITH TIME ZONE,
    last_run_at          TIMESTAMP WITH TIME ZONE,
    last_run_status      VARCHAR(20) DEFAULT 'idle',
    consecutive_failures INT DEFAULT 0,
    last_error           TEXT,

    PRIMARY KEY (device_id, profile_id),

    CONSTRAINT fk_dmt_device  FOREIGN KEY (device_id)  REFERENCES devices(id)            ON DELETE CASCADE,
    CONSTRAINT fk_dmt_profile FOREIGN KEY (profile_id) REFERENCES monitoring_profiles(id) ON DELETE CASCADE,
    CONSTRAINT chk_dmt_status CHECK (last_run_status IN ('idle', 'running', 'ok', 'failed'))
);

CREATE INDEX idx_dmt_next_run ON device_monitoring_tasks(next_run_at) WHERE is_enabled = TRUE;
CREATE INDEX idx_dmt_device   ON device_monitoring_tasks(device_id);
CREATE INDEX idx_dmt_profile  ON device_monitoring_tasks(profile_id);


-- ==================================================================
-- SECTION 21 : GESTION DES FIRMWARES (REPOSITORY)
-- ==================================================================

DROP TABLE IF EXISTS firmware_compatibility CASCADE;
DROP TABLE IF EXISTS firmware_images CASCADE;

CREATE TABLE firmware_images (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firmware_id     INT NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    checksum_hash   VARCHAR(128),
    hash_type       VARCHAR(10) DEFAULT 'SHA256',
    file_size_bytes BIGINT,
    storage_path    VARCHAR(255),
    is_recommended  BOOLEAN DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT fk_image_firmware    FOREIGN KEY (firmware_id) REFERENCES firmwares(id) ON DELETE CASCADE,
    CONSTRAINT uq_firmware_filename UNIQUE (filename)
);

CREATE TABLE firmware_compatibility (
    firmware_image_id INT NOT NULL,
    device_model_id   INT NOT NULL,

    PRIMARY KEY (firmware_image_id, device_model_id),

    CONSTRAINT fk_compat_image FOREIGN KEY (firmware_image_id) REFERENCES firmware_images(id) ON DELETE CASCADE,
    CONSTRAINT fk_compat_model FOREIGN KEY (device_model_id)   REFERENCES device_models(id)   ON DELETE CASCADE
);

CREATE INDEX idx_firmware_images_fw ON firmware_images(firmware_id);
CREATE INDEX idx_compat_model       ON firmware_compatibility(device_model_id);


-- ==================================================================
-- SECTION 22 : GESTION DES MAPS
-- ==================================================================

CREATE TABLE IF NOT EXISTS maps (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT,
    is_default  BOOLEAN DEFAULT FALSE,
    created_by  INT,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT uq_map_name UNIQUE (name)
);


CREATE TABLE IF NOT EXISTS map_devices (
    map_id      INT  NOT NULL,
    device_id   UUID NOT NULL,
    pos_x       FLOAT DEFAULT 0,
    pos_y       FLOAT DEFAULT 0,
    is_pinned   BOOLEAN DEFAULT FALSE,

    PRIMARY KEY (map_id, device_id),
    
    CONSTRAINT fk_md_map    FOREIGN KEY (map_id)    REFERENCES maps(id)    ON DELETE CASCADE,
    CONSTRAINT fk_md_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);


-- ==================================================================
-- TRIGGERS : MISE À JOUR AUTOMATIQUE updated_at
-- ==================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- Section 1
CREATE TRIGGER update_auth_snmp_modtime     BEFORE UPDATE ON auth_snmp      FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_auth_cli_modtime      BEFORE UPDATE ON auth_cli       FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_auth_profiles_modtime BEFORE UPDATE ON auth_profiles  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 2
CREATE TRIGGER update_device_groups_modtime BEFORE UPDATE ON device_groups  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 3
CREATE TRIGGER update_vendors_modtime           BEFORE UPDATE ON vendors           FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_device_categories_modtime BEFORE UPDATE ON device_categories FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_device_families_modtime   BEFORE UPDATE ON device_families   FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_device_models_modtime     BEFORE UPDATE ON device_models     FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_locations_modtime         BEFORE UPDATE ON locations         FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_racks_modtime             BEFORE UPDATE ON racks             FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 4
CREATE TRIGGER update_ref_device_status_modtime BEFORE UPDATE ON ref_device_status FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_firmwares_modtime         BEFORE UPDATE ON firmwares         FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_devices_modtime           BEFORE UPDATE ON devices           FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_device_modules_modtime    BEFORE UPDATE ON device_modules    FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 5
CREATE TRIGGER update_interfaces_modtime BEFORE UPDATE ON interfaces FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_vlans_modtime      BEFORE UPDATE ON vlans      FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 6
CREATE TRIGGER update_vrfs_modtime        BEFORE UPDATE ON vrfs        FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_ip_subnets_modtime  BEFORE UPDATE ON ip_subnets  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_ip_addresses_modtime BEFORE UPDATE ON ip_addresses FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 9
CREATE TRIGGER update_providers_modtime BEFORE UPDATE ON providers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_circuits_modtime  BEFORE UPDATE ON circuits  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 10
CREATE TRIGGER update_contracts_modtime BEFORE UPDATE ON contracts FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 11
CREATE TRIGGER update_app_users_modtime BEFORE UPDATE ON app_users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 12
CREATE TRIGGER update_auth_providers_modtime BEFORE UPDATE ON auth_providers FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 13
CREATE TRIGGER update_access_policies_modtime BEFORE UPDATE ON access_policies FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 16
CREATE TRIGGER update_logs_retention_policy_modtime BEFORE UPDATE ON logs_retention_policy FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 19
CREATE TRIGGER update_scan_profiles_modtime BEFORE UPDATE ON scan_profiles FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_scan_networks_modtime BEFORE UPDATE ON scan_networks FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- Section 21
CREATE TRIGGER update_firmware_images_modtime BEFORE UPDATE ON firmware_images FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();